### ISSUE TITLE
Pinch to zoom

### ISSUE THREAD

**Issue by BluePixel4k** [daniebeler/pixelix#65]
A pinch-to-zoom feature for pictures would be nice.

Thank you for the awesome app :)

**Comment by Hiebeler** [comment]
Thanks for the suggestion! We will definitely implement it in an upcoming update.

**Comment by Hiebeler** [comment]
The feature is now implemented in the new update, thanks for the request.

**Comment by BluePixel4k** [comment]
Thank you, it works really well 👍

**Comment by piratenpanda** [comment]
Could this be improved to have a permanent zoom instead of having to have your fingers on the display?
